### PR TITLE
backport "Refactor the class inclusions and chaining #239" to 4.3-stable

### PR DESCRIPTION
**Pull request by evgeni**
required to fix http://projects.theforeman.org/issues/19938 in 3.4.z

### CODE REVIEW

**Comment by evgeni** [comment]
You mean https://github.com/Katello/katello-installer/commit/1a1754678bf19b5002737b6143bcddf70c370059? We could, but it does not hurt to keep that hook for now, right?

**Comment by ekohl** [comment]
> You mean Katello/katello-installer@1a17546? We could, but it does not hurt to keep that hook for now, right?

It does hurt in my experience. It removes the file in the pre hook on proxies. Sometimes yum installs the file, apache starts and is broken. Only then pulp is configured and this file is created, but since apache failed to start the installer run is broken anyway.

**Comment by evgeni** [comment]
The hook replaces the file, not deletes it, so RPM should never update it.

That's exactly the reason it does that, and not just wipes the file :)

**Comment by ekohl** [comment]
I recall that the file is actually used on the proxy config and I ran into issues with it but I should look into it again to be sure.

**Comment by ehelms** [comment]
This looks like it needs test fixes?

**Comment by ekohl** [comment]
@ehelms for that we need to pin versions in ```.fixtures.yml``` so they are Puppet 3 compatible.

**Comment by ekohl** [comment]
What's the status here?

**Comment by evgeni** [comment]
/me sleeping ;)

let me have another look today

**Comment by evgeni** [comment]
obsolete after https://github.com/Katello/puppet-pulp/commit/59ee6fed7d11cbbf139656bdefd1d006aacba989

**Pull request closed without merging**
