### PR TITLE
do not specify ca cert in apache pulp.conf

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by beav** [comment]
@jlsherrill  typo in commit msg

**Comment by jlsherrill** [comment]
@beav hah good catch!

**Comment by beav** [comment]
is this line needed to validate that entitlement certs are signed when making requests for content?

**Comment by jlsherrill** [comment]
@beav which line exactly?

**Comment by jlsherrill** [comment]
@beav oh!  It should be specified by the virtual host controlling 443 as well

**Comment by beav** [comment]
@jlsherrill i see it now. Thanks!!

ACK from me

**Pull request merged**
