### PR TITLE
Allow newer puppetlabs-concat

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ehelms** [comment]
Looks like puppet-qpid needs an update?

**Comment by ekohl** [comment]
I'm guessing that it's because puppetlabs-concat 4.0.1 is installed but then puppet-qpid 2.2.0 wants a 2.x version so it breaks. Should we release 2.2.1 which allows concat 4.0?

**Comment by alexjfisher** [comment]
Commit message typo could be confusing?

**Comment by ekohl** [comment]
At least the branch name is correct ...

**Comment by ekohl** [comment]
I tried hacking around it but it looks like the module helper for beaker isn't flexible at all since it doesn't recognize an already installed version.

**Comment by ekohl** [comment]
💚

**Pull request merged**
