### PR TITLE
fixes #9479: fix usage with centos

### PR DESCRIPTION
**Pull request by dustints**

### CODE REVIEW

**Comment by dustints** [comment]
deb users?

**Comment by dustints** [comment]
same logic as before just inclusive of CentOS...
previously deb users were going to fall into the default/fail category.

**Comment by ehelms** [comment]
Ack

**Comment by ekohl** [comment]
:+1:

**Comment by iNecas** [comment]
:+1: This also seems to fix the travis failings on all the puppet modules that include this one

**Pull request merged**
