### PR TITLE
Drop puppet-foreman in favor of extlib for cache_data

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ekohl** [comment]
I'm not sure this is a good idea till puppet-foreman has dropped cached_data. Users might still end up with both modules in their environment and the incorrect version could be used.

**Comment by ehelms** [comment]
I think this can be reviewed now that puppet-foreman has been bumped to 5.0.0 in master

**Comment by ekohl** [comment]
:+1:

**Comment by stbenjam** [comment]
ACK

**Pull request merged**
