### PR TITLE
refs #15217 - puppet 4 support

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like the ```$::mongodb_version``` fact isn't set in the tests.

**Comment by ekohl** [comment]
ACK when Travis is green

**Comment by stbenjam** [comment]
@ekohl https://github.com/Katello/foreman-installer-modulesync/pull/7 json needs pinning now too

**Comment by stbenjam** [comment]
Green, thanks!

**Pull request merged**
