### PR TITLE
Require qpidd to be started before migrating the database.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by cristi1979** [comment]
I think that this belongs in broker.pp, because we don't know the broker type.

**Comment by ehelms** [comment]
@cristi1979 good call -- updated to move it into the broker

**Comment by cristi1979** [comment]
We also need to switch the order of the broker and database includes in init.pp

**Comment by ehelms** [comment]
Good catch, tests for the win! Updated, should pass this go around.

**Comment by cristi1979** [comment]
And it should be Exec[migrate_pulp_db]

**Comment by ehelms** [comment]
Damn. I should not be allowed to edit puppet modules before 11 am.

**Comment by cristi1979** [comment]
It looks good for me.

**Comment by ehelms** [comment]
Thanks for the review @cristi1979

**Pull request merged**
