### PR TITLE
Fix typo in variable name in params.pp

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by ehelms** [comment]
Blast, seems to be more failing now.

**Comment by stbenjam** [comment]
`root_home` is a fact from stdlib, @ekohl How do you handle these? They're not included in the os_facts hashes, as they're from puppetlabs-stdlib.  Should we just add them to the hash ourselves? Seems less than ideal, what happens next time puppetlabs-mongodb uses a stdlib - maybe we could come up with a better solution?

**Comment by ekohl** [comment]
@stbenjam we do the same with the concat tmpdir so I think we should do the same here.

**Comment by ehelms** [comment]
Looks like the Puppet 4 jobs failed needing this to be updated too:

https://github.com/Katello/puppet-pulp/blob/master/spec/defines/pulp_child_fragment_spec.rb#L15

**Comment by ehelms** [comment]
ACK

**Comment by stbenjam** [comment]
THANKS!

**Pull request merged**
