### PR TITLE
fixes #12033: set topic_exchange using the messaging_topic_exchange param

### PR DESCRIPTION
**Pull request by bbuckingham**

### CODE REVIEW

**Comment by stbenjam** [comment]
APT

**Comment by ehelms** [comment]
I was going to ask for an entry in the server.conf test for this content but it appears the config spec test doesn't have that at the moment.

**Comment by stbenjam** [comment]
Yea the spec is pretty basic :-( If @bbuckingham wants to, but I thought it'd be a lot to ask to add entirely new coverage

**Comment by bbuckingham** [comment]
@ehelms, @stbenjam, I added a test for the server.conf entry.

**Comment by ehelms** [comment]
ACK

**Comment by stbenjam** [comment]
Thanks :-)

**Pull request merged**
