### PR TITLE
install extra packages in case of qpid broker

### PR DESCRIPTION
**Pull request by cristi1979**

### CODE REVIEW

**Comment by ehelms** [comment]
I am missing where `pulp::consumer` gets called by the main pulp init.pp class.

**Comment by cristi1979** [comment]
Nowhere. I want to make a new PR with a new parameter (enable_nodes) that will include the consumer class.

Consumer class is not required on a normal pulp server.

**Comment by ehelms** [comment]
Will that fix the issue I am seeing where with the parameters PR I can't do a basic puppet apply of the pulp class? e.g. `puppet apply -e "class {pulp: }" ?  Currently that fails because of this package not being installed.

**Comment by cristi1979** [comment]
Sorry, I misunderstood what you said. I thought that goferd throws errors because of the missing package.

**Pull request closed without merging**
