### PR TITLE
Update the README

### PR DESCRIPTION
**Pull request by ekohl**
Still not very good, but an improvement aimed to address https://github.com/Katello/puppet-pulp/issues/143 and https://github.com/Katello/puppet-pulp/issues/241.

@rammaram06 @rgarrigue @djjudas21 if you could have a look then that'd great.

### CODE REVIEW

**Comment by rammaram06** [comment]
@ekohl this looks good..would you be able to add an example on how to setup ssl configuration?

**Comment by ekohl** [comment]
I've added some SSL examples, but haven't tested it yet. Looks like I'm still missing some of the settings on the messaging.

**Comment by djjudas21** [comment]
This looks much more useful. I'll try it out properly tomorrow - thanks!

**Comment by rgarrigue** [comment]
Some suggestions

- There's a debug parameter, document it and explain where's the output if
it's a specific file (as opposed to puppet output)
- Document emails settings (email_enabled email_from email_host email_port)
- In issue #164 we mention pulp rpm repo management, as far as I'm
concerned it's mandatory for pulp standalone installation (w/o katello), it
ought to be mentionned too
- default_login and default_password can be mentionned, with the default
value (admin / random pwd)
- Add a quick exemple to open firewall port with crayshfix's firewalld
module, since it's all about centos 7

That's it for what I'm doing. Reading the params.pp, an example with a
proxy configuration might interest people too

Best regards,


2017-05-22 17:25 GMT+02:00 Jonathan <notifications@github.com>:

**Comment by ekohl** [comment]
I'm trying to simplify the usage of the admin in https://github.com/Katello/puppet-pulp/pull/248. Once that's in I'm going to expand the README.

**Comment by ekohl** [comment]
Updated.

> - There's a debug parameter, document it and explain where's the output if it's a specific file (as opposed to puppet output)

I'm not sure what these exactly do so I've left them out for now.

> - Add a quick exemple to open firewall port with crayshfix's firewalld module, since it's all about centos 7

Personally I've always used the puppetlabs-firewall module so I'm leaving this out for now. I could mention the ports used.

> That's it for what I'm doing. Reading the params.pp, an example with a proxy configuration might interest people too

I noticed we have the parameter ```proxy_url``` which maps to ```proxy_host``` in the config. @ehelms you added this in 6388c094f735c6a59d2ab3440d5e8b6f8051cfc9 so can you have a look?

**Comment by ehelms** [comment]
@ekohl guessing it was a bit of a typo when configuring this for use with Katello's installer

**Comment by ekohl** [comment]
Given we're going to do a major version, shall we change it to ```proxy_host```?

**Comment by ekohl** [comment]
I'd like to get his merged on Tuesday because even if this is still incomplete, I think it's better than what we have now. Please point out any mistakes though. Suggestions for additions are also welcome and will be addressed in a separate PR.

**Pull request merged**
