### PR TITLE
add a simple login/logout provider

### PR DESCRIPTION
**Pull request by cristifalcas**
a simple provider to login/logout a pulp user

### CODE REVIEW

**Comment by cristi1979** [comment]
This is useless. I can't figure it out how to determine if the correct user has already logged in.

**Comment by cristi1979** [comment]
This was changed to always login the user: exists? returns always false.

**Comment by cristi1979** [comment]
A side effect of this is that logout will never be triggered. But, since I also force a logout in exists...

It doesn't look like a proper provider. Maybe an exec will be more useful instead?

**Comment by cristi1979** [comment]
Anyway, this is a sample usage:

	  pulp_login { 'admin': pass => 'admin' } ->
	  pulp_rpmrepo { 'epel':
	    ensure           => 'present',
	    validate         => true,
	    remove_missing   => true,
	    serve_http       => true,
	    retain_old_count => 5,
	    relative_url     => "epel/6Server",
	    feed             => 'http://dl.fedoraproject.org/pub/epel/6/x86_64/',
	  } ->
	  pulp_login { 'admin_logout': ensure => absent }

**Comment by ekohl** [comment]
I'm not sure how useful this is since I don't know pulp well enough, but shouldn't ```pulp_rpmrepo``` handle the authentication? I know this is hard problem (since we have a similar problem with foreman types through the API), but this solution feels like imperative programming in a declarative language.

**Comment by cristifalcas** [comment]
It's not useful at all, since it's only a hidden exec.

**Comment by ekohl** [comment]
Should we close this? Refactor this into something more useful?

**Comment by cristifalcas** [comment]
I will close it

**Pull request closed without merging**
