### PR TITLE
Fixes #20865 - correct profiling configuration

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by ekohl** [comment]
Thanks! I took the liberty of fixing the typo in the commit message when merging.

**Comment by iNecas** [comment]
Thanks!

**Comment by akofink** [comment]
Could we cut a release of puppet-pulp that includes this change for Katello 3.5.0 RC1?

**Comment by ekohl** [comment]
@akofink For simplicity I'm going to do a 5.1.0 release which includes all changes. 3/4 are good fixes and the 4th doesn't hurt.

**Pull request merged**
