### PR TITLE
Fixes #14361 - Setting a couple missing squid options

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by beav** [comment]
the squid docs say that both the new options are available in 3.0 and 3.1

test run worked for me, settings applied OK and squid restarted OK

```
[ INFO 2016-03-28 11:53:17 main]  cache_peer_access              PulpStreamer allow all
[ INFO 2016-03-28 11:53:17 main] +minimum_object_size            0 kB
[ INFO 2016-03-28 11:53:17 main] +range_offset_limit             none
[ INFO 2016-03-28 11:53:17 main]  Computing checksum on file /etc/squid/squid.conf

```

patch appears to not cause any issues, looks good to me

**Comment by mccun934** [comment]
@beav squid-3.3.8-26.el7.x86_64 and squid-3.1.23-9.el6.x86_64 are the latest so these should be OK

**Comment by beav** [comment]
@mccun934 oh weird, I was thinking of the wrong versions then, works the same in any event though :cat2:

**Comment by bbuckingham** [comment]
+1, the changes look sane.  I am going to run a sync test of EL6 on my config as well.

**Comment by daviddavis** [comment]
@bbuckingham :+1: thanks!

**Comment by bbuckingham** [comment]
From basic installer and sync tests on EL6 and EL7, I haven't seen any issues.  ACK from me.

**Comment by daviddavis** [comment]
@bbuckingham thanks again.

@Katello/installer can I get a merge?

**Comment by ehelms** [comment]
Thanks @daviddavis !

**Pull request merged**
