### PR TITLE
fix template :undef checks and yum proxy variables

### PR DESCRIPTION
**Pull request by walkamongus**
Supercedes #114

### CODE REVIEW

**Comment by ehelms** [comment]
Generally looks OK to me. Could you squash into a single commit?

**Comment by walkamongus** [comment]
I will squash. There was discussion in #114 regarding whether this will handle empty strings or not. I believe Puppet < 4.0.0 equates an empty string to undef but in > 4.0.0, empty strings are true. If parameters should be strings and not empty, this should be part of the parameter validations in init.pp.

I can add those validations in if it is desired.

**Comment by ehelms** [comment]
You'll need a rebase here after it was updated for Pulp 2.8

**Comment by walkamongus** [comment]
rebased and converted remaining undef check to the "new" method

**Comment by ehelms** [comment]
ACK - thanks @walkamongus !

**Pull request merged**
