### PR TITLE
make pulp streamer optional

### PR DESCRIPTION
**Pull request by cerealcake**
make pulp_streamer installation optional and include apache::mod::proxy in the event that pulp_streamer is included with the apache config added in https://github.com/Katello/puppet-pulp/commit/3e9195baca54a50745b591e16ac8ff501134d26a

### CODE REVIEW

**Comment by ehelms** [comment]
@cfouant @daviddavis can you double check this still meets your needs?

**Comment by ekohl** [comment]
The change itself looks good. I don't see any changes to the vhost configuration but I don't think that includes any streamer config anyway.

**Comment by cerealcake** [comment]
Noticed this is only required if not using a version greater or equal to Pulp-2.8.0, as pulp-streamer is available with this version.

I believe this can be closed as https://repos.fedorapeople.org/pulp/pulp/stable/ now includes Pulp-2.8.

**Comment by ekohl** [comment]
The ```include ::apache::mod::proxy``` is something we should add.

**Comment by stbenjam** [comment]
Needs rebase

**Comment by cerealcake** [comment]
As per my comment above https://repos.fedorapeople.org/pulp/pulp/stable/ now includes Pulp-2.8. which includes pulp-streamer.

For an item which is available on stable, it may not require to be optional anymore.

**Pull request closed without merging**
